name: amplify_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_gen_runner: ^4.1.6
  build_runner: ^2.1.8

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_gen:
  integrations:
    flutter_svg: true
